/**
 * CodeCraft — React Entry Point
 *
 * Mounts the React application and registers the PWA service worker.
 * The service worker is auto-generated by vite-plugin-pwa (Workbox)
 * and enables offline caching for the entire application.
 *
 * @see Project-Plan.md TASK-16 — PWA setup
 */

import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles/globals.css';
import './styles/editor.css';

// ─── Mount React App ─────────────────────────────────────────

const rootElement = document.getElementById('root');

if (!rootElement) {
  throw new Error('Root element not found. Cannot mount CodeCraft.');
}

createRoot(rootElement).render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// ─── Register PWA Service Worker (TASK-16) ───────────────────
// vite-plugin-pwa auto-generates the registerSW.js script.
// In production, it handles service worker registration + auto-update.
// In development, it's a no-op (devOptions.enabled = false).

if ('serviceWorker' in navigator) {
  // The service worker registration is handled by the plugin's
  // virtual module. We use the dynamic import approach so the
  // registration script is only included in production builds.
  import('virtual:pwa-register')
    .then(({ registerSW }) => {
      registerSW({
        onNeedRefresh() {
          // A new version is available. In Phase 1, show a toast.
          console.log('[PWA] New version available. Refresh to update.');
        },
        onOfflineReady() {
          // App is cached and ready for offline use.
          console.log('[PWA] App is ready for offline use.');
        },
        onRegisteredSW(_swUrl: string, registration: ServiceWorkerRegistration | undefined) {
          // Check for updates every hour in the background
          if (registration) {
            setInterval(() => {
              registration.update();
            }, 60 * 60 * 1000); // 1 hour
          }
        },
        onRegisterError(error: Error) {
          console.error('[PWA] Service worker registration error:', error);
        },
      });
    })
    .catch(() => {
      // virtual:pwa-register not available (e.g., dev mode without SW)
      // This is expected and harmless.
    });
}
