/// <reference types="vite/client" />

// Vite client types + custom environment type declarations

interface ImportMetaEnv {
  readonly GITHUB_PAGES?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

// ─── vite-plugin-pwa virtual module declaration ──────────────────
// Required for TypeScript to recognize the virtual:pwa-register import.
// This module is auto-generated by vite-plugin-pwa at build time.

declare module 'virtual:pwa-register' {
  export interface RegisterSWOptions {
    onNeedRefresh?: () => void;
    onOfflineReady?: () => void;
    onRegisteredSW?: (swUrl: string, registration: ServiceWorkerRegistration | undefined) => void;
    onRegisterError?: (error: Error) => void;
  }

  export function registerSW(options?: RegisterSWOptions): (reloadPage?: boolean) => Promise<void>;
}
